### ISSUE TITLE
A question regarding EventBus.removeHandler(handler)

### ISSUE THREAD

**Issue by manuprathab** [sockeqwe/Vaadin-MVP-Lite#4]
This method does not work correct, even after I removed a handler it's getting fired I hope there is a minor bug. But please let me know if this is already fixed, but when I downloaded latest jar, this bug is still there ! Can you please check this? and I am not using Vaadin 7

**Comment by manuprathab** [comment]
I found the fixed code, hope I can use the source itself !

**Comment by sockeqwe** [comment]
Hi you are right, the issue has been fixed in the source code. The current available Jar does not include this bugfix yet. I will upload a new jar version. Thank you for reporting!

**Comment by sockeqwe** [comment]
Hi
a new jar version that includes a bugfix for EventBus.removeHandler() is available in Vaadins Addon Directory.
